package com.ra.repository;

import com.ra.model.entities.Department;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface DepartmentRepository extends BaseRepository<Department> {
    // The existsByName() method is automatically generated by Spring Data JPA
    // It checks if there exists any Department with a matching name parameter
    // Returns true if exists, false if not exists
    // Used to validate that department names are not duplicated
    boolean existsByName(String name);

    // JPQL query to search Departments by name
    // - SELECT d FROM Department d: Get all fields from Department
    // - d.status = true: Only get active Departments
    // - :name IS null: If name parameter is null, this condition is always true
    // - lower(d.name) like lower(concat('%', :name, '%')): Case-insensitive name
    // comparison
    // and search by contains (contains substring)
    // - Pageable pageable: Support pagination of results
    @Query("SELECT d FROM Department d where d.status = true AND (:name IS null or lower(d.name) like lower(concat('%', :name, '%') ) )")
    Page<Department> searchDepartments(@Param("name") String name, Pageable pageable);
}
